
update GM_ZAKUPY_VAT set
NETTO = (select ILOSC_PO*CENA_ZAKUPU_NETTO_PO from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
VAT = (select ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
BRUTTO = (select (ILOSC_PO*CENA_ZAKUPU_NETTO_PO)+(ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100)) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001')
where GM_ZAKUPY_VAT.ID_FZ=(select ID from GM_FZ where GM_FZ.NUMER= 'FZ/2020/04/CE/0001');



update GM_ZAKUPY_VAT set
NETTO = (select ILOSC_PO*CENA_ZAKUPU_NETTO_PO from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
VAT = (select ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
BRUTTO = (select (ILOSC_PO*CENA_ZAKUPU_NETTO_PO)+(ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100)) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001')
where GM_ZAKUPY_VAT.ID_PZ= (select GM_PZ.ID from GM_PZ where GM_PZ.ID_FZ=(select ID from GM_FZ where GM_FZ.NUMER= 'FZ/2020/04/CE/0001')); 