update GM_FZ set
PLN_KWOTA_VAT_PO=0,
PLN_WARTOSC_BRUTTO_PO=0,
PLN_WARTOSC_NETTO_PO=0,
SPOSOB_LICZENIA=1,
WARTOSC_ROZRACHUNKU=0,
WAL_WARTOSC_NETTO_PO=0,
WAL_KWOTA_VAT_PO=0,
WAL_WARTOSC_BRUTTO_PO=0
where GM_FZ.NUMER= 'FZ/2020/04/CE/0001';