update GM_FZ set
PLN_KWOTA_VAT_PO=(select ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
PLN_WARTOSC_BRUTTO_PO=(select (ILOSC_PO*CENA_ZAKUPU_NETTO_PO)+(ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100)) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
PLN_WARTOSC_NETTO_PO=(select ILOSC_PO*CENA_ZAKUPU_NETTO_PO from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
SPOSOB_LICZENIA=0,
WARTOSC_ROZRACHUNKU=(select (ILOSC_PO*CENA_ZAKUPU_NETTO_PO)+(ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100)) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
WAL_WARTOSC_NETTO_PO=(select ILOSC_PO*CENA_ZAKUPU_NETTO_PO from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
WAL_KWOTA_VAT_PO=(select ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
WAL_WARTOSC_BRUTTO_PO=(select (ILOSC_PO*CENA_ZAKUPU_NETTO_PO)+(ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100)) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001')
where GM_FZ.NUMER= 'FZ/2020/04/CE/0001';

update GM_PZ set
WARTOSC_NETTO_ZAKUPU_PO=(select ILOSC_PO*CENA_ZAKUPU_NETTO_PO from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
KWOTA_VAT_ZAKUPU_PO=(select ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
WARTOSC_BRUTTO_ZAKUPU_PO=(select (ILOSC_PO*CENA_ZAKUPU_NETTO_PO)+(ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100)) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001'),
SPOSOB_LICZENIA=0,
WARTOSC_ROZRACHUNKU=(select (ILOSC_PO*CENA_ZAKUPU_NETTO_PO)+(ILOSC_PO*CENA_ZAKUPU_NETTO_PO*(STAWKA_ZAKUPU_PO/100)) from GM_FZ join GM_FZPOZ on GM_FZ.ID=GM_FZPOZ.ID_GLOWKI where GM_FZ.NUMER= 'FZ/2020/04/CE/0001')
where ID_FZ=(select ID from GM_FZ where GM_FZ.NUMER= 'FZ/2020/04/CE/0001');